'use strict';

require.config({
    baseUrl: 'js',
    waitSeconds: 0,
    paths: {
        ember: 'libs/ember.canary.min',
        emberValidator: 'libs/ember-validations-0.2.1.min',
        emberPageble: 'libs/ember-pageable',
        emberFlash: 'libs/ember-flash',
        handlebars: 'libs/handlebars-1.3.0.min',
        text: 'libs/text-loader-plugin',
        Q: 'libs/q',
        underscore: 'libs/underscore-min',
        httpClient: 'libs/http-client',
        httpClientSync: 'libs/http-client-synchronous',
        moment: 'libs/moment.min',
        jsEncrypt: '../assets/js/jsencrypt.min',
        sigma: 'libs/sigma.min',
        ueditor: '../assets/js/kotg/ueditor.all',
        ueditorConf: '../assets/js/kotg/ueditor.config',
        ueditorParse: '../assets/js/kotg/ueditor.parse',
        jabberService: 'jabber-application',
        raphael :"libs/raphael_customized_for_ember",
        vkmApp : 'vkmMain',
		xbbcode : 'libs/xbbcode',
        'jqui': 'libs/vkm/libs/jquery-ui-1.9.2.min',
    },
    
    shim: {
        ember: {
            deps: ['handlebars'],
            exports: 'Ember'
       
        },
        jabberService: {
            exports: 'jabberService'
        },
        underscore: {
            exports: '_'
        },
        handlebars: {
            exports: 'handlebars'
        },
        emberValidator: {
            deps: ['ember'],
            exports: 'EmberValidator'
        },
        emberFlash: {
            deps: ['ember', 'app'],
            exports: 'EmberFlash'
        },
      
        ueditor:{
            deps:['ueditorConf','ueditorParse'],
            exports:'ueditor'
        },
        emberPageble: {
            deps: ['ember', 'app'],
            exports: 'emberPageble'
        }
    }
});

require([
	'google-analytics-config',
    'ga-analytics',
    'ember',
    'emberValidator',
    'emberFlash',
    'Q',
    'underscore',
    'jsEncrypt',
    'services/encryptionService',
    'httpClient',
    'httpClientSync',
	'services/collaboration/userDetails',
    'app',
    'services/jabberUsersService',
    'services/configurationsService',
    'controllers/jabber/jabberMixin',
    'applicationController',
    'ember-helpers',
    'ember-application-helpers',
    'sigma',
    'ueditor',
    'raphael',
    'vkmMain',
    'xbbcode',

    'objects/community',
    'objects/admin/userManagementExpertiseItem',
    'libs/jquery.fileDownload',
    
    'views/people/popOverView',
    'views/people/multiSelectView',
    'views/people/userListItemView',
    'views/people/managerUserListItemView',
    'views/people/userTileItemView',
    'views/people/managerUserTileItemView',
    'views/chatRoom/chatRoomView',
    'views/chatSession/chatSessionView',
    'views/admin/userManagementUsersView',
    'views/admin/userManagementRolesView',
    'views/communitiesAllView',
    'views/communitiesCreateView',
    'views/communitiesView',
    'views/communityEditView',
    'views/communityDetailTitleView',
    'views/communityDetailAuthorView',
    'views/communityDetailTagsView',
    'views/communityDetailDescriptionView',
    'views/communityDetailDiscussionView',
    'views/communityDetailBlogsView',
    'views/communityDetailCommentView',
    'views/communityDetailWikisView',
    'views/communityDetailDocumentsView',
    'views/communityDetailMembersView',
    'views/community/communityView',
    'views/community/communityDetailsView',
    'views/community/communityBlogsView',
    'views/community/communityDiscussionsView',
    'views/community/communityWikisView',
    'views/community/communityDocumentsView',
    'views/community/communityFilesView',
    'views/community/communityMembersView',
    'views/community/communityPlaybookview',
    'views/community/communityJoinrequestView',
    'views/community/communityProxiesView',	
    'views/community/communityFoundationalView',
    'views/community/communitySpecializedView',
    'views/community/communityTransformationalView',
    'views/documents/documentDetailTitleView',
    'views/documents/documentDetailAuthorView',
    'views/documents/documentDetailTagsView',
    'views/documents/documentDetailDescriptionView',
    'views/documents/documentDetailCommentsView',
    'views/documents/documentDetailSharesView',
    'views/documents/documentsMyView',
    'views/admin/userManagementExpertiseView',
    'views/admin/userManagementRegistrationsView',
    'views/rssFeeds/emptyRssfeedsView',
    'views/rssFeeds/rssfeedItemsView',
    'views/rssFeeds/rssfeedsCreateView',
     'views/rssFeeds/rssfeedsEditView',
    'views/rssFeeds/rssfeedsIndexView',
    'views/rssFeeds/rssfeedsView',
    'views/leftNav/knowledgeCenterView',
    'views/leftNav/formalLearningView',
    'views/leftNav/mobileFolderView',
    'views/leftNav/collaborationView',
    'views/leftNav/adminLeftNavView',
    'views/leftNav/peopleLeftNavView',
    'views/leftNav/homeLeftNavView',
    'views/leftNav/managerView',
    'views/formallearning/myEnrollments',
    'views/formallearning/courseDetails',
	'views/formallearning/quiz',
    'views/formallearning/trainingCatalog',
	'views/formallearning/learningPlanView',
    'views/formallearning/shared',
    'views/formallearning/plpDetails',
    'views/organization/myTeam',


    'routes/admin/userManagementUsersRoute',
    'routes/admin/userManagementRolesRoute',
    'routes/communitiesIndexRoute',
    'routes/communitiesRoute',
    'routes/communitiesAllRoute',
    'routes/communitiesCreateRoute',
    'routes/communitiesMyRoute',
    'routes/communityRoute',
    'routes/community/communityPlaybookRoute',
    '',
    'routes/communityEditRoute',
    'routes/community/communityDetailsRoute',
    'routes/community/communityBlogsRoute',
    'routes/community/communityDiscussionsRoute',
    'routes/community/communityWikisRoute',
    'routes/community/communityDocumentsRoute',
    'routes/community/communityFilesRoute',
    'routes/community/communityMembersRoute',
    'routes/community/communityJoinrequestRoute',
    'routes/community/communityProxiesRoute',
    'routes/community/communityFoundationalRoute',
    'routes/community/communitySpecializedRoute',
    'routes/community/communityTransformationalRoute',
    'routes/documents/documentsRouteMixin',
    'routes/documents/documentsMyRoute',
    'routes/admin/userManagementExpertiseRoute',
    'routes/admin/userManagementRegistrationsRoute',
    'routes/rssFeeds/rssfeedItemsRoute',
    'routes/rssFeeds/rssfeedsRoute',
     'routes/rssFeeds/rssfeedsEditRoute',
    'routes/formallearning/myEnrollments',
    'routes/formallearning/courseDetails',
	'routes/formallearning/quiz',
    'routes/formallearning/trainingCatalog',
	'routes/formallearning/learningPlanRoute',
    'routes/formallearning/shared',
    'routes/formallearning/plpDetails',
    'routes/organization/myTeam',
    
    'components/viewFileComponentMixin',
    'components/bootstrapTagsInputComponent',
    'components/videoPlayerComponent',
    'components/readLinkComponent',
    'components/courseListItemComponent',
    'components/downloadLinkComponent',
    'components/readerLinkComponent',
    'components/viewFileComponent',
    'components/endorsementComponent',
    'components/fileChooserComponent',
    'components/fileUploadComponent',
    'components/visualSearchComponent',
    'components/catalogFilterComponent',
    'components/paginationComponent',
	'components/communityPaginationComponent',
    'components/cloudletTagsInputComponent',
    'components/textAreaComponent',
    'components/inputTextComponent',
    'components/sortingComponent',
    'components/jabberChatComponent',
	'components/reportComponent',
	
	  'controllers/admin/userManagementController',
	  'controllers/admin/mobileController',
	  'controllers/admin/systemController',
	  'controllers/admin/collaborateController',

    'controllers/admin/systemPreferencesController',
    'controllers/admin/roleAddController',
    'controllers/admin/userManagementRoleItemController',
    'controllers/people/peoplePopoverToggleMixin',
    'controllers/admin/userManagementExpertiseItemController',
    'controllers/admin/userManagementExpertiseController',
    'controllers/admin/userManagementRegistrationsController',
    'controllers/admin/userManagementRegistrationItemController',
    'controllers/admin/sysAdminStatesController',
    'controllers/jabber/chatRoomController',
    'controllers/collaboration/utils/confirmDeletDialogMixin',
    'controllers/collaboration/utils/fileUploadMixin',
    'controllers/communities/communityItemController',
    'controllers/communities/communityListingController',
    'controllers/communitiesCreateController',
    'controllers/communityEditController',
    'controllers/community/communityController',
    'controllers/community/communityDiscussionsController',
    'controllers/community/communityBlogsController',
    'controllers/community/communityWikisController',
    'controllers/community/communityDocumentsController',
    'controllers/community/communityFilesController',
    'controllers/community/communityMembersController',
    'controllers/community/communityProxiesController',	
    'controllers/community/communityPlaybookController',
    'controllers/community/communityFoundationalController',
    'controllers/community/communitySpecializedController',
    'controllers/community/communityTransformationalController',
    'controllers/utils/entitlements',
    'controllers/utils/dateUtil',
    'controllers/utils/sharesUtil',
    'controllers/utils/statsUtil',
    'controllers/utils/popoverUtils',
    'controllers/utils/stringUtils',
    'controllers/utils/webexUtils',
    'controllers/utils/shareDocumentsMixin',
    'controllers/utils/postsShareActivityBuilderUtil',
    'controllers/utils/actjsonutil',
    'controllers/utils/acteventutil',
    'controllers/utils/actemberutil',
    'controllers/utils/vkmuiUtil',
	'controllers/utils/communityUtils',
	'controllers/utils/notificationUtils',
	'controllers/utils/courseUtils',
    'controllers/leftNavController',
    'controllers/settingsController',
    'controllers/trendingTopicsController',
    'controllers/trendingTopicController',
    'controllers/breadcrumbsController',
    'controllers/landingController',
    'controllers/search/searchControllerMixin',
    'controllers/searchController',
    'controllers/search/usersSearchController',
    'controllers/search/coursesSearchController',
    'controllers/search/groupsSearchController',
    'controllers/search/postsSearchController',
    'controllers/search/documentsSearchController',
    'controllers/search/otgSearchController',
    'controllers/activityController',
    'controllers/collaboration/blogsController',
    'controllers/collaboration/questionsController',
    'controllers/collaboration/wikisController',
    'controllers/profile/profileImageUploadController',
    'controllers/profile/profileController',
    'controllers/recommendationItemController',
    'controllers/admin/operationAdminController',
    'controllers/admin/adminModelController',
    'controllers/admin/adminCategoriseController',
    'controllers/admin/adminCategoriesController',
    'controllers/admin/adminBlogProxyAssignment',
    'controllers/admin/adminTopicItemController',
    'controllers/homeController',
    'controllers/pulseController',
    'controllers/welcomeController',
    'controllers/userItemController',
    'controllers/admin/userManagementUsersController',
    'controllers/admin/roleViewPermissionsController',
    'controllers/admin/deleteRoleController',
    'controllers/admin/roleEditPermissionsController',
    'controllers/admin/userManagementRolesController',
	'controllers/admin/systemLicenseBatchController',
    'controllers/admin/reportsUsageController',
    'controllers/admin/reportsController',
    'controllers/topNavController',
    'controllers/notificationController',
    'controllers/jabber/chatSessionController',
	'controllers/formallearning/learningPlanController',
    'controllers/formallearning/trainingCatalog',
    'controllers/formallearning/courseItem',
    'controllers/formallearning/courseDetails',
    'controllers/formallearning/myEnrollments',
	'controllers/formallearning/quiz',
    'controllers/formallearning/shared',
    'controllers/formallearning/plpDetails',
    'controllers/jabber/jabberItemController',
    'controllers/jabber/jabberStatusPillController',
    'controllers/kotg/myTagsController',
    'controllers/kotg/myContactsController',
    'controllers/admin/adminMobileFolderController',
    'controllers/newkotg/helpers',
    'controllers/newkotg/fileuploadController',
    'controllers/newkotg/collectionsController',
    'controllers/newkotg/collectionController',
    'controllers/newkotg/notesController',
    'controllers/newkotg/noteController',
    'controllers/newkotg/notesAddController',
    'controllers/newkotg/noteController',
    'controllers/newkotg/noteEditController',
    'controllers/newkotg/sharedsController',
    'controllers/newkotg/sharedController',
    'controllers/kotg/drivesController',
    'controllers/kotg/driveController',
    'controllers/kotg/oauthController',
    'controllers/followedUserActivitiesController',
    'controllers/rssFeeds/rssfeedsController',
    'controllers/rssFeeds/createRssfeedModalController',
    'controllers/rssFeeds/rssfeedCreateController',
    'controllers/rssFeeds/rssfeedEditController',
    'controllers/documentsController',
    'controllers/documents/documentsControllerMixin',
    'controllers/documents/documentsCatalogController',
    'controllers/documents/documentsSharedController',
    'controllers/documents/documentsMyController',
    'controllers/documents/documentController',
    'controllers/documents/documentEditController',
    'controllers/documents/documentShareController',
    'controllers/confirmationController',
    'controllers/documents/fileUploadController',
    'controllers/documents/fileUnavailableController',
    'controllers/documents/videoPlayerController',
    'controllers/people/peopleController',
    'controllers/people/contactsController',
    'controllers/people/expertUsersController',
    'controllers/admin/adminUploadUsersController',
    'controllers/admin/seedUsersController',
    'controllers/admin/adminUploadExpertiseController',
    'controllers/profileNotificationController',
    'controllers/myFileUploadsController',
    'controllers/searchCourseItemController',
    'controllers/helpController',
    'controllers/featureUnavailableController',
    'controllers/streamactivity/activityController',
    'controllers/organization/myTeam',
    'controllers/managerUserItemController',


    'controllers/organization/playBooksController',
    'controllers/myAccountController',
    'controllers/sitemetric/sitemetricController',
    'controllers/tnc/tncController',
    'controllers/admin/passwordResetController',
    'controllers/webexItemController',
    'utils/documentUtils',
    //'controllers/formallearning/adminreportsController',
    'controllers/admin/adminAllactivitiesController',
    'controllers/organization/pendingApprovals',
    'routes/organization/pendingApprovals',
    'views/organization/pendingApprovals',
	'controllers/admin/reportsEnrollmentsController',
	'controllers/admin/reportsLearniningPlansController'
]);